#%RAML 1.0
title: information
/hello:
  get:
    description: 
    queryParameters:
      name:
        type: string
        description: the name of 
        maxLength: 10
        required: false
        example: dell
  