#%RAML 1.0
title: information
/hello:
  get:
    description: 
    queryParameters:
      name:
        type: string
        description: name of a preson
        maxLength: 10
        required: false
        example: hayat
  
  